language: php
php:
  - 7.3
  - 7.4
  - 8.0
sudo: false
services:
  - mysql
  - memcached
install:
  - composer install
before_script:
  - if [ $DB = 'mysql' ]; then mysql -e 'create database psx;'; fi;
script:
  - vendor/bin/phpunit
  - vendor/bin/psalm
env:
  - DB=mysql
  - DB=sqlite
