language: php
dist: trusty
php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
services:
  - mysql
  - memcached
before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi;
install:
  - composer install
  - composer require doctrine/orm ~2.5
  - composer require twig/twig ~1.16
before_script:
  - if [ $DB = 'mysql' ]; then mysql -e 'create database psx;'; fi;
script:
  - vendor/bin/phpunit
env:
  - DB=mysql
  - DB=sqlite
